version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    command: sh -c "npx prisma migrate dev && npx prisma generate && npm start"
    depends_on:
      - mysql
   

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: shopperAdmin2023
      MYSQL_DATABASE: shopper
      MYSQL_USER: shopperUser2023
      MYSQL_PASSWORD: shopperUser2023
    ports:
      - "3307:3306"
